### ISSUE TITLE
"Failed to collect dependencies at org.dcache...." during mvn package

### ISSUE THREAD

**Issue by Eugeniu-N** [dCache/nfs4j#103]
I'm trying to build a project using this dependency
```
<dependency>
    <groupId>org.dcache</groupId>
    <artifactId>nfs4j-core</artifactId>
    <version>0.19.0</version>
</dependency>
```
  
I also added the repository to my pom:
```
<repositories>
    <repository>
        <id>dcache-releases</id>
        <name>dCache.ORG maven repository</name>
        <url>https://download.dcache.org/nexus/content/repositories/releases</url>
        <layout>default</layout>
    </repository>
</repositories>
```

When I try to build my java project with `mvn clean package` I get `Could not resolve dependencies for project myproject:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.dcache:nfs4j-core:jar:0.19.0 -> com.sleepycat:je:jar:7.3.7`

I found a similar issue #98 involving the same je dependency but the problems are different

**Comment by kofemann** [comment]
Hm, can you try with 

```
https://download.dcache.org/nexus/repository/public/
```

**Comment by Eugeniu-N** [comment]
Yes, that solved the problem and now the project is being compiled successfully

**Comment by kofemann** [comment]
Thanks.

**Comment by 3c71** [comment]
I have a similar issue trying to use this library in an Android project, included in gradle like this:

`implementation 'org.dcache:nfs4j-core:0.26.0'
`
It fails to build with:

`Could not find org.dcache:nfs4j-core:0.26.0
`

Tried with 0.19.0 to no avail.

Do I need to download source code entirely?

**Comment by kofemann** [comment]
Yeah, we haven't published our jars ti maven central. It's on our todo list.
