### ISSUE TITLE
NFS client problem with mkdir

### ISSUE THREAD

**Issue by evial** [dCache/nfs4j#109]
Hi @kofemann. First of all, thanks for the library. I know the nfs4j client is for testing purpose but is the mkdir command supposed to work properly ?  list, read or remove commands work fine for me but mkdir returns a NFS4ERR_BADXDR error. Thanks

Connected to: Mr. X
pNFS MDS: true
pNFS  DS: false
Using slots: 160
server lease time: 90 sec.
root fh = 010007006901840000000000f801431ede424caabe33eed3d46f1df1
Server supported layout types: []
Layout type LAYOUT4_NFSV4_1_FILES not supported. Disabling pNFS
NFSv41: mkdir myFolder
NFSv41: umount
mkdir failed: NFS4ERR_BADXDR(10036)

**Comment by kofemann** [comment]
Hi @evial ,

sorry for the late reply....

Can you bit elaborate on the issues. I will be interested in a packet capture with tcpdump:

` tcpdump -i any -w /tmp/nfs.pcap port 2049`

In you example, the NFS4ERR_BADXDR might coming from umount

**Comment by evial** [comment]
Hi @kofemann. Attached the pcap file. Client and server have respectively ip 192.168.1.19 and 192.168.1.75. 

Server exports file: ` /var/nfs        *(rw,no_root_squash,insecure)`.

Thanks 

[nfs.zip](https://github.com/dCache/nfs4j/files/7539338/nfs.zip)
`

**Comment by evial** [comment]
Works like a charm now. Thanks for the support
