### ISSUE TITLE
Simple hello "nfs4j" world java with main() class?

### ISSUE THREAD

**Issue by dfshelton** [dCache/nfs4j#127]
Hello!

Could you please add a nfs4j hello world style java class with a main(), so people can export a single directory tree directly after building the sources, and not write lots of code first.

**Comment by dfshelton** [comment]
hello?

**Comment by kofemann** [comment]
Hi @dfshelton,

There are two projects that provide such a 'hello world': https://github.com/kofemann/simple-nfs and https://github.com/kofemann/vfs4j
