### ISSUE TITLE
Implement rquota protocol

### ISSUE THREAD

**Issue by kofemann** [dCache/nfs4j#133]
Despite the fact that the NFS v4 protocol specifies attributes to query the quota (https://tools.ietf.org/html/rfc5661#section-5.8.2.28), the Linux client doesn’t implement it, as the quota is not associated with a user or a group.

To support classic user and group quotas, the rquota protocol can be implemented:

https://git.kernel.org/pub/scm/utils/quota/quota-tools.git/tree/rquota.x

**Comment by QiulanHuang** [comment]
Hell Tigran,

We have client complains the failure to get the quota from NFS v4 client with the following error. Is it related to the issue you described above?

```bash
quota: error while getting quota from chimerav4.usatlas.bnl.gov:/pnfs for user1 (id 101056): Connection refused
Disk quotas for user user1 (uid 101056): 

```
Any suggestions would be greatly appreciated.

Thanks,
Qiulan

**Comment by kofemann** [comment]
Hi Qiulan,

As the issue is saying, the nfs4j, which is used by dCache is not supporting quota protocol.

**Comment by QiulanHuang** [comment]
Hi Tigran,

Thanks for your prompt reply. 

I see. Now we use space tokens allocated for users and not quotas.
Looking forward to the new enhanced feature from dCache.


Thanks,
Qiulan
