### ISSUE TITLE
NFS V3 and Mount Clients?

### ISSUE THREAD

**Issue by amarcionek** [dCache/nfs4j#32]
Curious if any thought has been given to implementing an NFS V3 and MOUNT V1 RPC clients. As there is server side code here, presumably it would be easy to make client side RPC on top of it.  If anyone knows of a library that does this, I would be grateful.

I don't even need I/O capability at the moment.  Our use case is to simply enumerate exports on a server.   I'd like pure java so its not platform specific.

**Comment by kofemann** [comment]
if you simply need to dump export list then here is an example how to do that:

package org.dcache.nfs.v3;

import java.net.InetAddress;
import java.net.InetSocketAddress;
import org.dcache.nfs.v3.xdr.mount_prot;
import org.dcache.nfs.v3.xdr.mountbody;
import org.dcache.nfs.v3.xdr.mountlist;
import org.dcache.utils.net.InetSocketAddresses;
import org.dcache.xdr.IpProtocolType;
import org.dcache.xdr.OncRpcClient;
import org.dcache.xdr.RpcAuth;
import org.dcache.xdr.RpcAuthTypeNone;
import org.dcache.xdr.RpcCall;
import org.dcache.xdr.XdrTransport;
import org.dcache.xdr.XdrVoid;
import org.dcache.xdr.portmap.GenericPortmapClient;
import org.dcache.xdr.portmap.OncPortmapClient;

public class ShowMount {

    public static void main(String[] args) throws Exception {

        if (args.length != 2) {
            System.err.println("usage: ShowMount host");
            System.exit(1);
        }
        String host = args[0];

        OncRpcClient rpcClient;
        XdrTransport transport;

        // get address of mountd service
        rpcClient = new OncRpcClient(InetAddress.getByName(host), IpProtocolType.TCP, 111);
        transport = rpcClient.connect();

        OncPortmapClient portmapClient = new GenericPortmapClient(transport);
        String mouontdAddress = portmapClient.getPort(mount_prot.MOUNT_PROGRAM, mount_prot.MOUNT_V3, "tcp");
        rpcClient.close();

        System.out.println(mouontdAddress);
        InetSocketAddress address = InetSocketAddresses.forUaddrString(mouontdAddress);

        // returned listen address contains wildcard. replace it with the host name.
        address = new InetSocketAddress(host, address.getPort());

        // connect to mountd and cass dump
        rpcClient = new OncRpcClient(address, IpProtocolType.TCP);
        transport = rpcClient.connect();
        RpcAuth auth = new RpcAuthTypeNone();

        RpcCall call = new RpcCall(mount_prot.MOUNT_PROGRAM, mount_prot.MOUNT_V3, auth, transport);

        mountlist exports = new mountlist();
        call.call(mount_prot.MOUNTPROC3_DUMP_3, XdrVoid.XDR_VOID, exports);

        mountbody exportEntry = exports.value;
        while (exportEntry != null) {
            System.out.println(exportEntry.ml_hostname.value + " : " + exportEntry.ml_directory.value);
            exportEntry = exportEntry.ml_next.value;
        }

        rpcClient.close();
    }
}

The linrary was motly implemented as nfs server, but we can polish the client part as well, if required.

**Comment by amarcionek** [comment]
Thanks so much for the code snippet!  I think that will do.

I guess beyond this, I don't yet have a use case for a full client and so couldn't justify anyone's time toward it. Should that change, I could offer to contribute. I'll close for now and reopen if necessary in the future.

THANK YOU again for the code!

**Comment by phovsepian-seven10** [comment]
This code performs a DUMP whereas we needed an EXPORT (RFC1813). I changed the code in the following way in order to retrieve an export list as opposed to mount entries.

	    RpcCall call = new RpcCall(mount_prot.MOUNT_PROGRAM, mount_prot.MOUNT_V3, auth, transport);

	    exports exports = new exports();
	    call.call(mount_prot.MOUNTPROC3_EXPORT_3, XdrVoid.XDR_VOID, exports);

	    exportnode exportEntry = exports.value;
	    while (exportEntry != null) 
	    {
	        String strExportDir = exportEntry.ex_dir.value;
	        
	        System.out.println("Export Path: " + strExportDir);
	        
	        exportEntry = exportEntry.ex_next.value;
	    }

	    rpcClient.close();

**Comment by kofemann** [comment]
right, good catch!
