### ISSUE TITLE
Failure to connect to AWS EFS mounts

### ISSUE THREAD

**Issue by spullara** [dCache/nfs4j#35]
It looks like the client included within the project is unable to communicate with AWS's Elastic File System that supports NFSv4. Have you had any luck connecting to it? I initially got a minor version not supported error 10021, then tried using withMinorVersion(0) and was able to move onto an unsupported error when it attempts to do the exchange_id 10004. Not sure if it should be able to talk with it but the linux NFSv4 client works with it fine.

It would be amazing if this worked as you could then use EFS from AWS Lambda.

**Comment by spullara** [comment]
```
java -jar nfs4j-basic-client-0.13.0-SNAPSHOT-jar-with-dependencies.jar
Started the NFS4 Client ....
NFSv41: mount us-west-2a.fs-0fe10da6.efs.us-west-2.amazonaws.com
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.dcache.nfs.v4.client.Main.processSequence(Main.java:1199)
	at org.dcache.nfs.v4.client.Main.sendCompound(Main.java:1019)
	at org.dcache.nfs.v4.client.Main.exchange_id(Main.java:512)
	at org.dcache.nfs.v4.client.Main.mount(Main.java:478)
	at org.dcache.nfs.v4.client.Main.main(Main.java:159)
```

This is due to error 10021 — doesn't look like it is handled properly.

**Comment by spullara** [comment]
It looks like AWS EFS claims to support NFSv4.0.

**Comment by kofemann** [comment]
Well, the client is essentially for testing and talks NFSv4.0 only.  Doing IO with v4.0 is quite complicates. If you need metadata operations only (list, remove, getattr), then it's not hard to add/fix.

**Comment by spullara** [comment]
Ah I see. Your library was the closest thing I could find that could potentially work but it sounds like it is quite a ways from a complete client. Thanks.

**Comment by Hronom** [comment]
@spullara have you solve this?

**Comment by kofemann** [comment]
@Hronom can you provide errors that you see?
