### ISSUE TITLE
Add an example to REAMDE how to start the NFS server

### ISSUE THREAD

**Issue by krichter722** [dCache/nfs4j#4]
It is currently not clear how to start the server. `README` doesn't explain it and `java -jar target/jpnfs-0.5.10-jar-with-dependencies.jar` seems to require a config file named "SpringRunner" which is mentioned nowhere (`Spring: IOException parsing XML document from file [/root/jpnfs/target/SpringRunner]; nested exception is java.io.FileNotFoundException: SpringRunner (No such file or directory)` occurs at invokation of `java -jar target/jpnfs-0.5.10-jar-with-dependencies.jar SpringRunner`).

I experienced this trouble with git tag `jpnfs-0.5.10` after building with `mvn install`.

**Comment by kofemann** [comment]
a README file added by commit c8ddacaf1627875f6b35c28c9d6026edd0f1ece1
