### ISSUE TITLE
nfsv4 OperationWRITE has arbitrary limit on write offset + size

### ISSUE THREAD

**Issue by skoopys** [dCache/nfs4j#40]
OperationWRITE contains this code:

`
      if (_args.opwrite.offset.value + _args.opwrite.data.remaining() > 0x3ffffffe) {
            throw new InvalException("Arbitrary value");
      }
`

Which seems to prevent any write from succeeding where the offset + the size is greater than around 1GB.   Why does this limit exist?  What is the meaning of the "Arbitrary value" exception thrown in this instance?

**Comment by kofemann** [comment]
@skoopys Thanks. Fixed in 0addfd7
