### ISSUE TITLE
nfs3 server does not correctly handle utf-8 filenames

### ISSUE THREAD

**Issue by skoopys** [dCache/nfs4j#41]
When trying to cp files with chinese/japanese characters in them, the nfs3 server will replace anything that isn't US ASCII with ASCII 63 which is the question mark  - this appears to be caused by Xdr (in this case) decoding the strings as US ASCII using Java's string constructor in xdrDecodeString with Charset.US_ASCII as the second parameter.

If this NFS3 implementation is to follow the spec, I think it should either use UTF-8 or throw an error - as suggested by RFC 1813 section 3.2:

>    5. In general, there will be characters that a server will
>       not be able to handle as part of a filename. This set of
>       characters will vary from server to server and from
>       implementation to implementation.  In most cases, it is the
>       server which will control the client's view of the file system.
>       If the server receives a filename containing characters that it
>       can not handle, the error, NFS3ERR_EACCES, should be returned.
>       Client implementations should be prepared to handle this side
>       affect of heterogeneity.

**Comment by kofemann** [comment]
You are right, the xdrDecodeString decodes into ASCII. As UTF8 is backward compatible with ACSII, it makes sense to always decode as UTF8.

**Comment by skoopys** [comment]
I'd be happy to make a PR with that change (since it's simple) if you'd like

**Comment by kofemann** [comment]
sure! 
please add Sign-of-by

**Comment by skoopys** [comment]
I have made a PR here: https://github.com/dCache/oncrpc4j/pull/51

Let me know if there's anything you would like different

**Comment by kofemann** [comment]
the fix will be available with next update of oncrpc4j library

**Comment by kofemann** [comment]
solved by oncrpc4j-2.7.0 (02d6c9b3b814c53d8d71b421e2accf7c3aef2594)
