### ISSUE TITLE
Missing default implementation for NFSv41DeviceManager

### ISSUE THREAD

**Issue by dkocher** [dCache/nfs4j#49]
Since cbdaee9931e864de0f9c53f8f2f2c280e0a261c6 I am missing a default implementation for `NFSv41DeviceManager`.

**Comment by kofemann** [comment]
I am surprised that you are affected by that. The NFSv41DeviceManager used only for NFSv4.1/pNFS.

**Comment by dkocher** [comment]
We do not rely on pNFS but it is a constructor argument for `NFSServerV41`.

**Comment by kofemann** [comment]
A **null** should do the job. I will add a builder for NFSServerV1 to make creation of desired server much simpler.

**Comment by dkocher** [comment]
Confirmed that a `null` value works just fine.

**Comment by kofemann** [comment]
with current master (afd91506) you can update your code to do something like this:

```java
        NFSServerV41 nfs4 = new NFSServerV41.Builder()
                .withExportFile(exportFile)
                .withVfs(vfs)
                .withOperationFactory(new MDSOperationFactory())
                .build();
```

Which looks better (to my taste)
