### ISSUE TITLE
Missing directory entries

### ISSUE THREAD

**Issue by ylangisc** [dCache/nfs4j#50]
Hi,
There seems to be a bug in `OperationREADDIR#process` setting EOF to true too early. In my specific case I have 21 entries in my `DirectoryStream`. While processing the 21st and last entry the condition `(dircount + newDirSize > _args.opreaddir.dircount.value)` is true and due to the `break` the while loop is being leaved without processing the last entry. Since it was the last entry `!dirList.hasNext()` evaluates to false and thus `res.resok4.reply.eof` is set to true which is wrong. The last item got lost.

-Yves

**Comment by kofemann** [comment]
Hi Yves,

Thanks for the report.  We do have some unit tests which should have
catched that situation. I will check that.

Thanks,

-kofemann

**Comment by kofemann** [comment]
I have update unit test to handle this corner case. Good catch, thanks!

-kofemann
/** caffeinated mutations of the core personality */
