### ISSUE TITLE
support for xattr (rfc8276)

### ISSUE THREAD

**Issue by kofemann** [dCache/nfs4j#55]
[RFC 8276](https://tools.ietf.org/html/rfc8276) describes  'File System Extended Attributes in NFSv4'. This functionality may help to provide a standard way to internal metadata which is currently exposed through various magic files.

**Comment by paulmillar** [comment]
:+1:

**Comment by kofemann** [comment]
xattr support is added in version [0.20.0](https://github.com/dCache/nfs4j/releases/tag/nfs4j-0.20.0)
