### ISSUE TITLE
Can I force nfs client to perform lookup till current working directory? (trough error codes?)

### ISSUE THREAD

**Issue by aasenov** [dCache/nfs4j#69]
I'm using nfs4j with custom VFS implementation that uses file paths instead of Inode numbers. As Inode data is limited to 64/128 bytes, based on nfs version, I'm keeping cache with mapping between INode and file path. Everything works fine until I reboot the server and I loose this cache, as nfs client also use caching and it sends already cached inode values, but I'm unable to rebuild file path from inode itself. I disable all type of client cache (-o noac,lookupcache=none), but still there are cases that won't work. If I enter some sub-folder structure, restart the nfs server, and execute "ls -al" I get "ls: cannot open directory '.': Stale file handle", as the Inode is not in the cache and I'm unable to complete "getattr()" call. On the other hand, if I call  "ls -al <fullPath>", then the client correctly perform lookup for every path item and I'm able to rebuild the cache mappings and operation succeed.
So is there a way when you perform operation on invalid Inode, to force the client to perform those lookups? I've tried throwing StaleException in such cases, but without luck. Nfs client is v4.1.

**Comment by kofemann** [comment]
NFS spec assumes, that file handles are permanent. My guess will be as well to return ESTALE to enforce lookup. However, for directories this will mess-up client-side cache. May we you can try to implement persistent mapping with ehcache of hazelcast?

**Comment by aasenov** [comment]
I was unable to make client reload the cache, so I was forced to resolve the issue on the server side. As the VFS I'm using is relatively linked Parent->Child, I was able to store small portion of this relation in the Inode. When I receive Inode that's not in the cache, I perform manual lookups based on stored relations. For now this solves the issue, but if I run out of space in the Inode, there is no other option than storing mapping in persistent cache.
