### ISSUE TITLE
Mount Ok but no files present at client side

### ISSUE THREAD

**Issue by hassin23ayz** [dCache/nfs4j#81]
hello thanks for your library 
i was able to run nfs server under ubuntu here is my exports files 

`/home/ayx/AAA/nfs-Server *(rw,all_squash,sec=sys)`

at the client side i used the following mount command 

`$sudo mount.nfs -o nfsvers=4.1,nolock,noacl -rw -v 192.168.0.105:/home/ayx/AAA/nfs-Server nfs-Client`

the folder gets mounted but there are no files present 
what is that i am doing wrong ?

**Comment by kofemann** [comment]
I assume, that directory is not empty.....

**Comment by hassin23ayz** [comment]
thanks a Lot for your kind reply 

the directory has a text file of 33bytes in size 
this is my code snippet along with the folder and it's contents
![Selection_010](https://user-images.githubusercontent.com/5806239/66336785-986dac00-e95f-11e9-9c47-7fe96d0c00c0.png)

**Comment by hassin23ayz** [comment]
thanks a lot i am closing the issue , here is what i did to solve
![Selection_012](https://user-images.githubusercontent.com/5806239/66376126-b45d6600-e9d0-11e9-8e11-0244db2cb088.png)
